### ISSUE TITLE
Mejoras en el sistema con la base de datos

### ISSUE THREAD

**Issue by ManuelLR** [ManuelLR/Notmail_Bot#2]
# Movimiento de código
## Desde utils/database.py
Creo que el archivo recoge demasiada información. Según las buenas prácticas de python dice que cada clase en un archivo facilitando el mantenimiento. Esta sería mi propuesta:
- [x] `class EmailServer` debería moverse a `repository/emailServer.py`
- [x] `class User` debería moverse a `repository/user.py`
- [x] `class Account` debería moverse a `repository/account.py`
- [x] `def parseAccountsToJson` debería moverse a `repository/account.py`
- [x] `def parseJsonToAccounts` debería moverse a `repository/account.py`
- [x] `class DBC` a `repository/repository.py`. De esta forma solo habría que llamar a este método. Igualmente creo que habrá que tocar algo para que sea fácil usarlo desde todos los archivos pero cuando se intente unir más seriamente se verá.

Adicionalmente a esto... ¿sería interesante crear la típica sección domain?. Yo tengo el objeto `Message` dando por ahí la lata que no se donde ponerlo puesto que es algo que no persiste

## Desde config/testdb.py
La verdad es que no había planteado ningún sitio para poner los test por lo que esto habría que discutirlo (tanto lugar como como se hacen). Aquí hay dos formas de hacerlo, a lo `dp` o a lo `go`. `DP` ya sabemos como sería, crear una carpeta denominada `tests` en la raiz e ir organizando todo el código. En cambio, en `go` los test se ponen en la misma carpeta que el archivo que quieres probar y con el mismo nombre, por ejemplo, los test de `services/email.py` estarian en `services/emailTest.py`. A mi sinceramente la forma que más me convence es la de `DP` así puedes hacer cosas más genéricas y te centras en leer código pero para gustos... los colores.

# Conceptos en general
- [x] No existe unión entre los `Accounts` y los `EmailServer`. Creo que un account debería de soportar varios `EmailServer` puesto que el protocolo `imap` (el más usado para leer), no puede enviar mensajes por lo que haría falta otro y sería desde la misma cuenta.
- [x] No se como funciona la base de datos exactamente pero veo fundamental que haya un `id` en cada tabla puesto que será lo que le pasaríamos al cliente y nos facilitaría las cosas. Quizás se esté implementando de alguna forma que yo no haya visto.

# General
Muy buen diseño, le diste bastantes vueltas la verdad.

Hay una cosa que no acabo de tener clara. ¿Para que poner los getter y los setter?

**Comment by juanrarodriguez18** [comment]
Yo por mi la cerraría.
